[2024-05-18T10:19:14.172+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-18T10:19:14.315+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: mysql_table_dump.Python scheduled__2024-03-14T00:00:00+00:00 [queued]>
[2024-05-18T10:19:14.330+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: mysql_table_dump.Python scheduled__2024-03-14T00:00:00+00:00 [queued]>
[2024-05-18T10:19:14.332+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-05-18T10:19:14.371+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): Python> on 2024-03-14 00:00:00+00:00
[2024-05-18T10:19:14.388+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'mysql_table_dump', 'Python', 'scheduled__2024-03-14T00:00:00+00:00', '--job-id', '53', '--raw', '--subdir', 'DAGS_FOLDER/dump_load_dag.py', '--cfg-path', '/tmp/tmp7d6lkoyb']
[2024-05-18T10:19:14.402+0000] {standard_task_runner.py:91} INFO - Job 53: Subtask Python
[2024-05-18T10:19:14.406+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=585) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-18T10:19:14.407+0000] {standard_task_runner.py:63} INFO - Started process 588 to run task
[2024-05-18T10:19:14.677+0000] {task_command.py:426} INFO - Running <TaskInstance: mysql_table_dump.Python scheduled__2024-03-14T00:00:00+00:00 [running]> on host 84791bb03867
[2024-05-18T10:19:15.046+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='mysql_table_dump' AIRFLOW_CTX_TASK_ID='Python' AIRFLOW_CTX_EXECUTION_DATE='2024-03-14T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-14T00:00:00+00:00'
[2024-05-18T10:19:15.050+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-18T10:19:15.088+0000] {logging_mixin.py:188} INFO - <Task(MySqlOperator): mysql_task>
[2024-05-18T10:19:15.089+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-05-18T10:19:15.090+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-18T10:19:15.105+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=mysql_table_dump, task_id=Python, execution_date=20240314T000000, start_date=20240518T101914, end_date=20240518T101915
[2024-05-18T10:19:15.165+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-18T10:19:15.198+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-18T10:19:15.212+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-05-18T13:19:43.524+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-18T13:19:43.561+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: mysql_table_dump.Python scheduled__2024-03-14T00:00:00+00:00 [queued]>
[2024-05-18T13:19:43.580+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: mysql_table_dump.Python scheduled__2024-03-14T00:00:00+00:00 [queued]>
[2024-05-18T13:19:43.581+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-05-18T13:19:43.614+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): Python> on 2024-03-14 00:00:00+00:00
[2024-05-18T13:19:43.627+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'mysql_table_dump', 'Python', 'scheduled__2024-03-14T00:00:00+00:00', '--job-id', '61', '--raw', '--subdir', 'DAGS_FOLDER/dump_load_dag.py', '--cfg-path', '/tmp/tmpqk26hz7z']
[2024-05-18T13:19:43.630+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=219) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-18T13:19:43.631+0000] {standard_task_runner.py:91} INFO - Job 61: Subtask Python
[2024-05-18T13:19:43.631+0000] {standard_task_runner.py:63} INFO - Started process 221 to run task
[2024-05-18T13:19:43.678+0000] {task_command.py:426} INFO - Running <TaskInstance: mysql_table_dump.Python scheduled__2024-03-14T00:00:00+00:00 [running]> on host bf3113c643bb
[2024-05-18T13:19:43.766+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='mysql_table_dump' AIRFLOW_CTX_TASK_ID='Python' AIRFLOW_CTX_EXECUTION_DATE='2024-03-14T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-14T00:00:00+00:00'
[2024-05-18T13:19:43.767+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-18T13:19:43.868+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-18T13:19:43.869+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/mysql/connector/connection_cext.py", line 323, in _open_connection
    self._cmysql.connect(**cnx_kwargs)
_mysql_connector.MySQLInterfaceError: Unknown MySQL server host 'host.docker.local' (-2)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/read_data.py", line 5, in preporcess
    mydb = mysql.connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/mysql/connector/pooling.py", line 322, in connect
    return CMySQLConnection(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/mysql/connector/connection_cext.py", line 140, in __init__
    self.connect(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/mysql/connector/abstracts.py", line 1363, in connect
    self._open_connection()
  File "/home/airflow/.local/lib/python3.12/site-packages/mysql/connector/connection_cext.py", line 328, in _open_connection
    raise get_mysql_exception(
mysql.connector.errors.DatabaseError: 2005 (HY000): Unknown MySQL server host 'host.docker.local' (-2)
[2024-05-18T13:19:43.888+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=mysql_table_dump, task_id=Python, execution_date=20240314T000000, start_date=20240518T131943, end_date=20240518T131943
[2024-05-18T13:19:43.901+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 61 for task Python (2005 (HY000): Unknown MySQL server host 'host.docker.local' (-2); 221)
[2024-05-18T13:19:43.926+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-18T13:19:43.942+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-18T13:19:43.944+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-05-18T13:22:16.945+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-18T13:22:16.976+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: mysql_table_dump.Python scheduled__2024-03-14T00:00:00+00:00 [queued]>
[2024-05-18T13:22:16.983+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: mysql_table_dump.Python scheduled__2024-03-14T00:00:00+00:00 [queued]>
[2024-05-18T13:22:16.984+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-05-18T13:22:16.998+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): Python> on 2024-03-14 00:00:00+00:00
[2024-05-18T13:22:17.007+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'mysql_table_dump', 'Python', 'scheduled__2024-03-14T00:00:00+00:00', '--job-id', '62', '--raw', '--subdir', 'DAGS_FOLDER/dump_load_dag.py', '--cfg-path', '/tmp/tmp3w4hus38']
[2024-05-18T13:22:17.009+0000] {standard_task_runner.py:91} INFO - Job 62: Subtask Python
[2024-05-18T13:22:17.010+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=313) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-18T13:22:17.011+0000] {standard_task_runner.py:63} INFO - Started process 315 to run task
[2024-05-18T13:22:17.052+0000] {task_command.py:426} INFO - Running <TaskInstance: mysql_table_dump.Python scheduled__2024-03-14T00:00:00+00:00 [running]> on host bf3113c643bb
[2024-05-18T13:22:17.135+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='mysql_table_dump' AIRFLOW_CTX_TASK_ID='Python' AIRFLOW_CTX_EXECUTION_DATE='2024-03-14T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-14T00:00:00+00:00'
[2024-05-18T13:22:17.137+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-18T13:22:17.954+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-05-18T13:22:17.955+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-18T13:22:17.964+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=mysql_table_dump, task_id=Python, execution_date=20240314T000000, start_date=20240518T132216, end_date=20240518T132217
[2024-05-18T13:22:17.989+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-18T13:22:18.004+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-18T13:22:18.006+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
